#!/bin/sh

set -e
umask 0002

OPTIONS="--lock /etc/device/system/dns/ \
         --show - \
         --polar disabled \
         --default all --select-base /usr/share/device/state/system/dns/resolver/protocol.txt --select protocol"

if [ "$1" == "--" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

fi

