#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet disable unbound-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl --quiet disable unbound-keygen.service
  /usr/bin/sudo /usr/bin/systemctl --quiet disable unbound.service

  if test -f "disabled"; then
    echo "dns resolver is already disabled."
  elif test -f "enabled"; then
    touch "updated"
    mv "enabled" "disabled"
    /usr/bin/sudo /usr/bin/systemctl stop unbound-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl stop unbound-keygen.service
    /usr/bin/sudo /usr/bin/systemctl stop unbound.service
  fi

fi

