#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable unbound-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl --quiet enable unbound-keygen.service
  /usr/bin/sudo /usr/bin/systemctl --quiet enable unbound.service

  if test -f "enabled"; then
    echo "dns resolver is already enabled."
  elif test -f "disabled"; then
    touch "updated"
    mv "disabled" "enabled"
    /usr/bin/sudo /usr/bin/systemctl restart unbound-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl restart unbound-keygen.service
    /usr/bin/sudo /usr/bin/systemctl restart unbound.service
  else
    touch "updated"
    touch "enabled"
    echo "dns resolver will be enabled on next reboot."
  fi

fi

