#!/bin/bash

#
# Unbound DNS Server Autodiscovery - Resolver
# ===========================================
#
# This script autogenerates the unbound config for a local DNSSEC resolver.

set -e
umask 0007


#
# Handle resolver
# ---------------
#
# This works by replacing /etc/resolv.conf with a sylink of our own,
# which signals network manager and friends to not touch.

if test "$1" = "start"; then

  if test ! -f "/etc/device/system/dns/resolver/disabled.bin"; then

    # whatever this is, move it out the way
    if test -e "/etc/resolv.conf"; then
      mv "/etc/resolv.conf" "/etc/resolv.conf.orig"
    fi
    ln -s "/usr/libexec/device/system/dns/resolv.conf" "/etc/resolv.conf"

    logger -t unbound-autodiscovery "enabled unbound dns resolver."

  else

    if test -L "/etc/resolv.conf"; then
      rm -f "/etc/resolv.conf"
      if test -f "/etc/resolv.conf.orig"; then
        mv "/etc/resolv.conf.orig" "/etc/resolv.conf"
      fi
    fi

    logger -t unbound-autodiscovery "disabled unbound dns resolver."

  fi

elif test "$1" = "stop"; then

  if test -f "/etc/device/system/dns/resolver/disabled.bin"; then

    if test -L "/etc/resolv.conf"; then
      rm -f "/etc/resolv.conf"
      if test -f "/etc/resolv.conf.orig"; then
        mv "/etc/resolv.conf.orig" "/etc/resolv.conf"
      fi
    fi

    logger -t unbound-autodiscovery "disabled unbound dns resolver."

  fi

fi

