#!/bin/sh

set -e
umask 0002

OPTIONS="--show - --polar disabled --default all --select-base /usr/share/device/system/dns/resolver/protocol.txt --select protocol"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

